### ISSUE TITLE
Invalid target pos in PlannerSimple2D.computePath throws an error

### ISSUE THREAD

**Issue by AaronPB** [MRPT/mrpt#1067]
When giving an invalid target position, it throws an error instead of receiving notfound = true (or other status) so the script itself could handle it and not being interrupted.

Error:
Origin: (2.866,2.847,90.47deg)
Target: (-3.000,3.000,90.00deg)
Searching path...terminate called after throwing an instance of 'std::logic_error'
  what():  /build/mrpt-KfsiMU/mrpt-2.0.4~snapshot20200518-1423-git-3e8ecd67-bionic/libs/nav/src/planners/PlannerSimple2D.cpp:60: [void mrpt::nav::PlannerSimple2D::computePath(const mrpt::maps::COccupancyGridMap2D&, const mrpt::poses::CPose2D&, const mrpt::poses::CPose2D&, std::deque<mrpt::math::TPoint2D_<double> >&, bool&, float) const] Assert condition failed: target.x > theMap.getXMin() && target.x < theMap.getXMax() && target.y > theMap.getYMin() && target.y < theMap.getYMax()

**Comment by jlblancoc** [comment]
Done!
