### ISSUE TITLE
CPointsMapXYZI insertPoint issue

### ISSUE THREAD

**Issue by anosnowhong** [MRPT/mrpt#1068]
Hi, 
It seems there is no such method with 4 parameters, it is invoked [here](https://github.com/MRPT/mrpt/blob/develop/libs/maps/include/mrpt/maps/CPointsMapXYZI.h#L226). Base class CPointMaps only imply it with there parameters, and I can't find any other method in CPointsMapXYZI.

**Comment by jlblancoc** [comment]
Thanks for reporting! Please, check it out now after 524af0f532d96e9abd9f8d9ffd5ccaebc47fad42
