### ISSUE TITLE
How to solve "error: no type named 'Int32' in namespace       'testing::internal'"

### ISSUE THREAD

**Issue by Gatsby23** [MRPT/mrpt#1075]
![image](https://user-images.githubusercontent.com/18000675/89004813-9123ee80-d335-11ea-8023-30a4876f028e.png)

Hello, My computer is OSX10.15.6 and how to solve this ?

**Comment by jlblancoc** [comment]
Hi, 

Per https://github.com/google/googletest/issues/1519 , it seems it's related to c++17 flags. 
What's your version of cmake? 

Anyway, give it a try to the code in the branch [fix/cpp17-gtest](https://github.com/MRPT/mrpt/tree/fix/cpp17-gtest) I just pushed, and let me know if that fixes the problem.

**Comment by Gatsby23** [comment]
![image](https://user-images.githubusercontent.com/18000675/89099206-2e5b5180-d420-11ea-8bb0-877e4618f3db.png)
My CMake is 3.18.0, but it also fails in fix/cpp17-gtes this branch.

**Comment by jlblancoc** [comment]
What version of clang?

**Comment by danieldanciu** [comment]
I get the same error. 
OS: Catalina 10.15.3
clang version 9.0.0
cmake 3.15.4

Error:

```
/usr/local/include/gmock/internal/gmock-internal-utils.h:145:21: error: use of undeclared identifier 'Int64'
GMOCK_DECLARE_KIND_(Int64, kInteger);
                    ^
/usr/local/include/gmock/internal/gmock-internal-utils.h:146:21: error: use of undeclared identifier 'UInt64'
GMOCK_DECLARE_KIND_(UInt64, kInteger);
                    ^
In file included from /Users/dd/work/metagenome/metagraph/tests/annotation/row_diff/test_row_diff.cpp:2:
In file included from /usr/local/include/gmock/gmock.h:59:
/usr/local/include/gmock/gmock-actions.h:165:46: error: use of undeclared identifier 'UInt64'
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_(UInt64, 0);
                                             ^
/usr/local/include/gmock/gmock-actions.h:166:46: error: use of undeclared identifier 'Int64'
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_(Int64, 0);
                                             ^
In file included from /Users/dd/work/metagenome/metagraph/tests/annotation/row_diff/test_row_diff.cpp:2:
/usr/local/include/gmock/gmock.h:76:1: error: no type named 'Int32' in namespace 'testing::internal'
GMOCK_DECLARE_int32_(default_mock_behavior);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/gmock/internal/gmock-port.h:73:44: note: expanded from macro 'GMOCK_DECLARE_int32_'
    extern GTEST_API_ ::testing::internal::Int32 GMOCK_FLAG(name)
```

**Comment by danieldanciu** [comment]
A quick hack to work around the issue is to define
```
namespace testing {
namespace internal {
using UInt64 = uint64_t;
using Int64 = int64_t;
using Int32 = int32_t;
} // namespace internal
} // namespace testing
```

before including `gmock.h`

**Comment by Gatsby23** [comment]
> What version of clang?

![image](https://user-images.githubusercontent.com/18000675/89531272-8a5c1680-d822-11ea-81f9-e77f8bd07fb3.png)
My Clang version is 10.0

**Comment by jlblancoc** [comment]
Our CI uses Xcode-11.5 with C++ version (I guess it's apple clang?) version 11... 
It seems a bug in clang 9, right? Will try to include the patch proposed by @danieldanciu in a PR anyway...

**Comment by jlblancoc** [comment]
Will close due to the lack of follow-up. 

Please, reopen if it's still an issue with up-to-date OSX compilers.
