### ISSUE TITLE
SIFT is moved to the main repository

### ISSUE THREAD

**Issue by jiapei100** [MRPT/mrpt#1100]
1) Failed to build **mrpt** with the following **ERROR** message:

```console
error: ‘cv::xfeatures2d::SIFT’ has not been declared
```

2) Happen to notice that

```console
misc/python/shadow_sift.hpp:2:// SIFT is moved to the main repository
```

So, any plan to be compatible with the most recent **OpenCV**?

Cheers

**Comment by jlblancoc** [comment]
Thanks for the info! Yes, will address this one.
