### ISSUE TITLE
graph_tools's abnormal edge color

### ISSUE THREAD

**Issue by anosnowhong** [MRPT/mrpt#1111]
Hi,
When I try to plot the edge between nodes, the actually color of edge is strange(It seems always the same as background color, so it hard to observe it.) [this](https://github.com/MRPT/mrpt/blob/e0082aca4592aae38e36af35e454f733928dbc62/libs/opengl/include/mrpt/opengl/graph_tools_impl.h#L186) part of code might be the problem, After change it to 
`const mrpt::img::TColor col8bit(edge_color >> 8, edge_color & 0x000000ff);` It shows the correct default color (0x0000FF40).
The same problem may happends to "edge_rel_poses_color" as well.

**Comment by jlblancoc** [comment]
Obviously wrong, so bad...

Fixed now. Thanks!
