### ISSUE TITLE
Seg. fault using camera calibration

### ISSUE THREAD

**Issue by Svato** [MRPT/mrpt#1137]
(camera-calib:26510): Gtk-CRITICAL **: 18:30:55.746: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:55.746: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:55.840: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:55.845: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:55.854: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:55.855: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:58.320: gtk_window_resize: assertion 'height > 0' failed

(camera-calib:26510): Gtk-CRITICAL **: 18:30:58.377: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:58.377: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:58.421: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:30:58.423: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:31:52.015: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:31:52.015: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:31:52.023: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(camera-calib:26510): Gtk-CRITICAL **: 18:31:52.023: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
Segmentation fault (core dumped)

Any ideas how to solve this?
any number of images, any resolution

**Comment by jlblancoc** [comment]
Can you provide more details? 
- When does the crash exactly happen? (Steps to reproduce)
- OS and MRPT version.

**Comment by jlblancoc** [comment]
Closing for lack of feedback. Reopen if needed!

**Comment by Svato** [comment]
LINUX Mint mate / Win 10. 
I did follow video - https://www.youtube.com/watch?v=BkZkq6zPwQM
I did make 20 pictures. After pressing calibrate i got the segmentation error

**Comment by jlblancoc** [comment]
ok. Could you please share your 20 images in a zip as a comment attachment?

**Comment by Likhith-Sugganahalli** [comment]
Hi, i have run into the same problem, after taking the 15 frames, clicking on calibration starts the process, in the log, it detects all images, first couple of roll pitch statements are printed, and it crashes

![Screenshot from 2021-04-15 10-12-52](https://user-images.githubusercontent.com/44597096/114815400-bbd6aa00-9dd3-11eb-926f-cc8ee29c5bf9.png)

![Screenshot from 2021-04-15 10-13-13](https://user-images.githubusercontent.com/44597096/114815414-c002c780-9dd3-11eb-999c-e39631d2f768.png)

Where can i access the images from?

**Comment by jlblancoc** [comment]
Thanks! Fantastic, now I could reproduce the bug: indeed the problem only happens after grabbing the images from a live camera, I formerly only tested it against images in the disk and in that case it doesn't fail. 

I'll fix it soon.

**Comment by jlblancoc** [comment]
It's fixed now in `develop`, thanks for reporting!
