### ISSUE TITLE
Warning! PATH too long installer unable to modify PATH!

### ISSUE THREAD

**Issue by msqiu** [MRPT/mrpt#1152]
Face the warning: **Warning! PATH too long installer unable to modify PATH!**
Then I think I have to add the Path myself. But which PATHs need to be added to system variables?

**Comment by jlblancoc** [comment]
Hi,

I guess you are in Windows. Normally, if you are going to just use the precompiled apps, there's no need to add anything to PATH. 

If you want to compile your own programs, then you must add `ProgramFiles/mrpt-xxx/bin/` (if I recall it right) to `PATH`, so Windows can find all DLLs...
