### ISSUE TITLE
Why can't this version of the software show that the zip package is corrupted.  ? https://github.com/MRPT/mrpt/tree/0c3d605c3cbf5f2ffb8137089e43ebdae5a55de3

### ISSUE THREAD

**Issue by teng23333** [MRPT/mrpt#1154]
Why can't this version of the software show that the zip package is corrupted.  ?https://github.com/MRPT/mrpt/tree/0c3d605c3cbf5f2ffb8137089e43ebdae5a55de3

**Comment by jlblancoc** [comment]
Hi, 
Sorry, I don't get it... :-) 
What zip file?
Why are you interested in that particular version of mrpt? (it's quite old now!)

**Comment by teng23333** [comment]
Sorry. It's a problem with my browser, it can download normally now :-）
