### ISSUE TITLE
How to install mrpt in windows10 and vs2019?

### ISSUE THREAD

**Issue by Tokymin** [MRPT/mrpt#1159]
I just install the windows .exe package,but it's said the path of  system System environment variable is too long. I also tried to compile the source code of the MRPT using cmake, but there are so error to solve, it just drive me crazy...T T

**Comment by jlblancoc** [comment]
> ,but it's said the path of system System environment variable is too long

Hmm... Try the installer again **without** marking the option to "Add to system PATH".

**Comment by Tokymin** [comment]
> 
> 
> > ,but it's said the path of system System environment variable is too long
> 
> Hmm... Try the installer again **without** marking the option to "Add to system PATH".

thanks for your reply,I've configured it correctly in the VS2019 this afternoon,^ ^

**Comment by jlblancoc** [comment]
:+1:
