### ISSUE TITLE
CFFMPEG_Inputstream.cpp error during "cmake --build ."

### ISSUE THREAD

**Issue by ketchart** [MRPT/mrpt#1165]
https://ibb.co/sm3WLrF

The error appeares during "cmake --build ."

https://www.dropbox.com/s/wvckxx7kerawvtw/CMAKE_CONFIG.txt?dl=0

This CMAKE_CONFIG.txt is the result of:
cd mrpt
mkdir build && cd build
VERBOSE=1 cmake ..  | tee CMAKE_CONFIG.txt

**Comment by jlblancoc** [comment]
What Ubuntu version (or any other distro) are you using? It seems an issue with a particular version of avcodec, using a docker image of your distro for testing would be the best way to go...
