### ISSUE TITLE
The transform from IMU to camera

### ISSUE THREAD

**Issue by joegeng** [MRPT/mrpt#1169]
Hi Jose,
I download the Malaga Urban Dataset to study the SLAM, but i can not find the transform from IMU to Left camera, could you provide the pose to me?
Thank you very much!

**Comment by jlblancoc** [comment]
(For the records)

Hi,

That transformation can be obtained from Table 2 [here](https://ingmec.ual.es/~jlblanco/papers/blanco2013malaga_urban_dataset_IJRR_draft.pdf).

for example, building in Python / Matlab the 4x4 homogeneous matrix for the poses of the camera P_c and the IMU P_i, and doing: inv(P_i) * P_c.

Hope it helps.
