### ISSUE TITLE
Remove more 3rd party sources from release tarballs

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#1206]
- [x] 3rdparty/googletest/* -> libgtest-dev, libgmock-dev  ==> Done via 161d16c71fd1fcc21bd0d7d3934b84b850b48528
- [x] 3rdparty/nanogui/ext/nanovg/example/Roboto-*.ttf -> fonts-roboto   ==> Done via uscan d/copyright `Files-Excluded` since those files are not used at all in mrpt builds.
- [x] 3rdparty/glew/* -> libglew-dev ==> Via `Files-Excluded` too. Used for Windows builds exclusively.
- [x] 3rdparty/freeglut/* -> freeglut3-dev ==> Via `Files-Excluded` too. Already not used by cmake if the freeglut3-dev is found.
- [x] 3rdparty/glext/* -> libgl-dev  ==> Via `Files-Excluded` too. pkg already provided by build-dep `libglu1-mesa-dev`.
- [x] libs/math/src/CSparse/ -> libsuitesparse-dev ==> Via `Files-Excluded` too. Not used if libsuitesparse-dev is found (already a build-dep).

As suggested by @jspricke .

Alternatives (on the fly download / clone?) should be added for Windows users, I guess...

**Comment by jspricke** [comment]
>Alternatives (on the fly download / clone?) should be added for Windows users, I guess...

There are package managers for Windows, maybe they could provide the 
dependencies?

**Comment by jlblancoc** [comment]
@jspricke well, thanks to the d/copyright Files-Excluded feature, it was far easier than expected... only one patch needed for gtest, the rest are handled via d/copyright.
