### ISSUE TITLE
FATAL Error

### ISSUE THREAD

**Issue by shanchanggo** [MRPT/mrpt#1219]
when I try to cmake, the error appeared.so  what should i do .   Error:fatal:Your current branch 'master' has not been submitted yet.

**Comment by jlblancoc** [comment]
Try deleting your git cloned repo, and clone again with: 

    git clone https://github.com/MRPT/mrpt.git --recursive

**Comment by shanchanggo** [comment]
i try it. the new question appears.  cmakeoutput.log and cmakeerror.log make some problems.what should i do ,friend.
