### ISSUE TITLE
How to avoid using 3rdparty libraries under 3rdparty, but using system installed libraries?

### ISSUE THREAD

**Issue by jiapei-nexera** [MRPT/mrpt#1238]
Any configuration parameters for me to specify to avoid using 3rdparty libraries under 3rdparty, but using system installed libraries?

The **nanogui** seems to be ..... Hmmmm

**Comment by jlblancoc** [comment]
Hi, 
In general, the cmake scripts `script_*.cmake` [in this directory](https://github.com/MRPT/mrpt/tree/develop/cmakemodules) **first** try to find out system versions, then use embedded version only if the former is not found.

`nanogui` has no system package, as there are many forks around, including MRPT's own with custom changes, sorry...

You can also disable many of those dependencies by setting the `DISABLE_*` switches in cmake under "advanced variables".

**Comment by jiapei-nexera** [comment]
Successfully built... it looks it's just the issue `tinyxml2`, instead of `tinyxml` that **nanogui** relies on??? Thank you ...
