### ISSUE TITLE
mrpt-2.4.9 release is looking for git submodules ??????

### ISSUE THREAD

**Issue by jiapei-nexera** [MRPT/mrpt#1239]
```
 CMake Error at CMakeLists.txt:39 (message):
   git submodules missing! You probably did not clone the project with
   --recursive.  It is possible to recover by calling:

     git submodule update --init --recursive


 Configuring incomplete, errors occurred!
 See also "....../mrpt-2.4.9/build/CMakeFiles/CMakeOutput.log".
```

**Comment by jlblancoc** [comment]
What version did you download? Note that the .zip automatically published by GitHub indeed does not contain submodules. 
Either clone with `git` or get one the `mrpt-x.y.z.tar.gz` assets in Releases instead, which should ship all the submodules. 

If you still have problems with it, feel free of re-opening!
