### ISSUE TITLE
Missing documentation pages, or wrong links.

### ISSUE THREAD

**Issue by git-user44** [MRPT/mrpt#1252]
Trivial one. The URL https://www.mrpt.org/tutorials/programming/statistics-and-bayes-filtering/probability_density_distributions_over_spatial_representations/ has links to 4 other pages in poses::. None of the links work.

**Comment by jlblancoc** [comment]
Thanks! I know it... there are *many* doc pages in the need to get updated and fixed...

That link has been redirected to the new, [updated doc page](https://docs.mrpt.org/reference/latest/tutorial-pdf-over-poses.html).

Cheers,
