### ISSUE TITLE
Package 'libwxgtk3.0-dev' has no installation candidate

### ISSUE THREAD

**Issue by matthew-william-lock** [MRPT/mrpt#1253]
I have the following error when trying to build from source on Ubuntu 22.04

```
E: Package 'libwxgtk3.0-dev' has no installation candidate
```

[Potential reason](https://askubuntu.com/questions/1241217/package-libwxgtk3-0-dev-has-no-installation-candidate-on-ubuntu-20-04)

**Comment by jlblancoc** [comment]
Correct! Instructions updated here: 944fa880e2a04f0e0eea63519f846fc6c22b5f20

It was fixed in the official Debian repo [1 week ago](https://salsa.debian.org/robotics-team/mrpt/-/commit/fadd3ae6f810644b3d565a730928a54edbc591f3) but forgot to update the web.
