### ISSUE TITLE
Is there anyway to use this with PlatformIO for Teensy?

### ISSUE THREAD

**Issue by matthew-william-lock** [MRPT/mrpt#1254]
Hey !

I am looking to use the map functionality offered by mrpt for use on a Teensy 4.1.

Is there any way I can include mrpt in a PlatformIO project?

Thanks!

**Comment by jlblancoc** [comment]
Hi! I'm afraid the minimum entry level for MRPT is a RBPI or similar system, capable of a filesystem and a minimal Linux kernel...
