### ISSUE TITLE
Incorrect license and copyright for CSparse

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [MRPT/mrpt#1256]
The CSparse source code and include file (cs.h) have a header on each file that incorrectly imply that the package is under the BSD license, and that the package was written by the MRPT authors.  I've updated the license information and copyright information with the correct information.  All tests should pass since only comments are changed.  I didn't modify any source code.

See https://github.com/MRPT/mrpt/pull/1255

**Comment by jlblancoc** [comment]
Fixed via #1255 1255
