### ISSUE TITLE
How to build it with visual studio 2022 on windows11

### ISSUE THREAD

**Issue by zhengzh** [MRPT/mrpt#1272]
I followed the official tutorial to compile mrpt on windows11, but I am stuck in the step of building opengl and freeglut, many build errors occured. Could you give me a detaild tutorial on how to build mrpt on windows11 with visual studio 2022, thanks!

**Comment by jlblancoc** [comment]
Hi @zhengzh 

I tried it today with VS2022 out of the box and mrpt (+wxWidgets + opencv) built ok without issues. 
Note you DON'T need to build opengl nor freeglut yourself, just open the MRPT.sln project and build it from Visual Studio...
