### ISSUE TITLE
Does not build with an opencv where patch level > 15

### ISSUE THREAD

**Issue by git-user44** [MRPT/mrpt#1285]
As the title says, does not build when opencv has a patch level > 15. 

With opencv 3.4.19 it fails thus... (I added some code to print out various values just to find out what it was complaining about)

IN_VERSION="3.4.19"
PATCH="19"
DECCHAR2HEXVAL="3"
DECCHAR2HEXVAL="4"
DECCHAR2HEXVAL="19"
CMake Error at cmakemodules/UtilsMacros.cmake:79 (message):
  Invalid format for hexidecimal character
Call Stack (most recent call first):
  cmakemodules/UtilsMacros.cmake:95 (DECCHAR2HEX)
  cmakemodules/script_opencv.cmake:45 (VERSION_TO_HEXADECIMAL)
  CMakeLists.txt:299 (include)

-- Configuring incomplete, errors occurred!

**Comment by jlblancoc** [comment]
It was about time... :-)
Thanks for reporting. Just about to release a fix.
