### ISSUE TITLE
Extension of the mrpt::utils::TRuntimeClassId to support classes from different namespaces having identical names

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#14]
(Original report in Google code: https://code.google.com/p/mrpt/issues/detail?id=23 )

Reported by robert.schattschneider@pg.canterbury.ac.nz, Mar 1, 2012
If two objects from classes with identical names but different namespace are used, the run-time type identification is not able differ them, as only the classes' name but not their namespace is integrated in their class ID. Instead, the classes' namespace should be integrated, too. An example:

```
#define IMPLEMENTS_MRPT_OBJECT2(class_name, base, NameSpace, NameSpaceBase) \
            mrpt::utils::CObject* NameSpace::class_name::CreateObject() \
                { return static_cast<mrpt::utils::CObject*>( new NameSpace::class_name ); } \
            NameSpace::class_name##Ptr NameSpace::class_name::Create() \
                { return NameSpace::class_name##Ptr( new NameSpace::class_name ); } \
            const mrpt::utils::TRuntimeClassId* NameSpace::class_name::_GetBaseClass() \
                { return CLASS_ID_NAMESPACE(base, NameSpaceBase); } \
            mrpt::utils::TRuntimeClassId NameSpace::class_name::class##class_name = { \
                #NameSpace"::"#class_name, NameSpace::class_name::CreateObject, &class_name::_GetBaseClass }; \
            const mrpt::utils::TRuntimeClassId *NameSpace::class_name::classinfo = & NameSpace::class_name::class##class_name; \
            const mrpt::utils::TRuntimeClassId* NameSpace::class_name::GetRuntimeClass() const \
            { return CLASS_ID_NAMESPACE(class_name,NameSpace); } \
            mrpt::utils::CLASSINIT NameSpace::class_name::_init_##class_name(CLASS_ID_NAMESPACE(base, NameSpaceBase)); \
            mrpt::utils::CObject * NameSpace::class_name::duplicate() const \
            { return static_cast<mrpt::utils::CObject*>( new NameSpace::class_name(*this) ); }
```

**Comment by jolting** [comment]
Couldn't you do something with templates and avoid the macros?

I'm not sure if the following program is doing exactly what you're doing, but I hope it illustrates the point.

The following program prints:
```
c1
Foo::C<int>
B
ObjectBase

c2
Foo::C<float>
B
ObjectBase

c3
Foo::C<B>
B
ObjectBase

ptr
Foo::Bar::D
Foo::C<int>
B
ObjectBase
```


```c++
#include <iostream>
#include <typeinfo>
#include <string>
#include <memory>
#include <cxxabi.h>

std::string demangle(const char * mangled)
{
  std::string s;
  int status;
  char* demangledStr = abi::__cxa_demangle(mangled,
					 nullptr, nullptr,
					 &status);
  if(status == 0){
    s = demangledStr;
    free(demangledStr);
  }
  return s;  
}

class ObjectBase
{
public:
  class RuntimeInfoBase
  {
  public:
    virtual std::string name() const
    {
      return std::string(demangle(typeid(ObjectBase).name()));
    };
    virtual std::shared_ptr<ObjectBase> createPtr() const
    {
      return std::shared_ptr<ObjectBase> (new ObjectBase);
    };
  virtual const RuntimeInfoBase *baseId() const 
    {
      return NULL;
    };
  };
  virtual ~ObjectBase()
  {}
  
  static const RuntimeInfoBase &getClassStatic()
  {
    return classType_;
  }

  virtual const RuntimeInfoBase &getClass()
  {
    return classType_;
  }
private:
  static const RuntimeInfoBase classType_;

};



template <typename T, typename BASE>
class RuntimeInfo : public ObjectBase::RuntimeInfoBase
{
public:
  virtual std::string name() const
  {
    return std::string(demangle(typeid(T).name()));
  }
  virtual std::shared_ptr<ObjectBase> createPtr() const
  {
    return std::shared_ptr<ObjectBase> (new T());
  }

  virtual const ObjectBase::RuntimeInfoBase *baseId() const
  {
    return &BASE::getClassStatic();
  }
};

template <typename T, typename BASE>
class DeriveWithInfo : public BASE
{
public:
  static const ObjectBase::RuntimeInfoBase &getClassStatic()
  {
    return classType_;
  }
  virtual const ObjectBase::RuntimeInfoBase &getClass()
  {
    return classType_;
  }
private:
  static const RuntimeInfo<T, BASE> classType_;
};

/* heres the fun part */

class B : public DeriveWithInfo<B, ObjectBase>
{


};


namespace Foo{
  template<typename T>
  class C : public DeriveWithInfo<C<T>, B>
  {

  };
  namespace Bar{
    class D : public DeriveWithInfo<D, C<int>>
    {

    };
  }
}

/* instatiate the class info here */
template<typename T, typename B>
const RuntimeInfo<T, B> DeriveWithInfo<T, B>::classType_;
const ObjectBase::RuntimeInfoBase ObjectBase::classType_;


int main(int argc, char *argv[])
{
  Foo::C<int>   c1;
  Foo::C<float> c2;
  Foo::C<B>     c3;
  Foo::Bar::D    d;  

  ObjectBase *p = &d;
  
  std::cout << "c1" << std::endl;

  for(const ObjectBase::RuntimeInfoBase *cId = &c1.getClass();
      cId;
      cId = cId->baseId()) {
    std::cout << cId->name() << std::endl;
  }
  
  std::cout << std::endl;
  std::cout << "c2" << std::endl;

  for(const ObjectBase::RuntimeInfoBase *cId = &c2.getClass();
      cId;
      cId = cId->baseId()) {
    std::cout << cId->name() << std::endl;
  }

  std::cout << std::endl;
  std::cout << "c3" << std::endl;

  for(const ObjectBase::RuntimeInfoBase *cId = &c3.getClass();
      cId;
      cId = cId->baseId()) {
    std::cout << cId->name() << std::endl;
  }

  std::cout << std::endl;
  std::cout << "ptr" << std::endl;

  for(const ObjectBase::RuntimeInfoBase *cId = &p->getClass();
      cId;
      cId = cId->baseId()) {
    std::cout << cId->name() << std::endl;
  }

  return 0;
}

```

For visual studio I don't think you need to demangle the string. I've only tried to compile this with c++11.

**Comment by jolting** [comment]
Is this still an issue in MRPT 2.0?

https://github.com/MRPT/mrpt/commit/a35cd3d62519d429579ca7b24f91615bd88c9b66

**Comment by jlblancoc** [comment]
I actually didn't take any decision on this yet because... it's not become a real limitation (yet). I mean, unless there are real chances of having two classes with the same names, in different namespaces, the existing method "just works"... 

Still, doing things right is always an insurance to avoid future clashes! ;-)

My thoughts: 
* Yes, this is still an issue, even after your commit https://github.com/MRPT/mrpt/commit/a35cd3d62519d429579ca7b24f91615bd88c9b66 , because `CLASS_ID_NAMESPACE()` is solved, but the class name collision between `Foo::C` vs. `Bar::C` is not (AFAIK ?) in the 2.0 branch.

* The obvious solution is to use a code like yours above to always serialize the fully qualified name instead of the plain class name. 
  * Pros: clashes avoided!
  * Cons: inefficiency (yes... I can't avoid this! I'm from a generation that programmed ASM code in a 1-2 kBs uControllers :-P ) ; **backwards compatibility**.

The latter is a real issue for me. We must be able to load old datasets, where de-serialization expect non-fully qualified class names. 

I only can think of an intermediary solution: 
* to serialize new objects using the fully-qualified name approach (and hope that GZ-compressed streams will alleviate the loss of efficiency, or just assume it's a little price to pay),
* call `registerClass()` twice for each class, with short and long names, so we can read old and new formats.

Just thinking aloud...

Thoughts?

**Comment by jolting** [comment]
Either intermediary solution I think will work.

Eventually, I think that serialization should be overhauled, but I would wait until c++ has compile time type reflection[1]. Then for backward compatibility, I would put all the old serialization code int a separate library.

1. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0194r1.html

**Comment by jlblancoc** [comment]
Great times for C++ ! Thanks for the pointer, hope it becomes part of the std soon. 

On top of that lib, a new lib could be written to handle serialization (binary, XML, Yaml,...), including some mechanism for *versioning* (I'm kind of obsessed with that topic, but I'm convinced it's really important to ensure persistence of data logs). 
This could be an independent, reusable, great project on its own, though...

**Comment by jlblancoc** [comment]
I think this one can be closed (at last, since March 2014!!), since the new module [mrpt-typemeta](http://mrpt.ual.es/reference/dev-module-refactor/group__mrpt__typemeta__grp.html) is now able to handle class names incl. namespaces. It remains to integrate it with serialization, but work will go on within #615
