### ISSUE TITLE
python bindings via apt

### ISSUE THREAD

**Issue by NikolausDemmel** [MRPT/mrpt#142]
The wiki page for python bindings mention that apt-installable python bindings are planned. Any idea when this might happen?

**Comment by sem23** [comment]
When I have some time near future I will talk to JL how to do this. When I've written the bindings I think I already have prepared this. As mentionened I will have a look soon!

If you have tested/used the bindings, it would be nice to get some feedback!

**Comment by jlblancoc** [comment]
Finally, python bindings are in `master`. A new issue has been opened for creating proper Debian packages, in the future, if time permits... ;-)

**Comment by jlblancoc** [comment]
Closed, since it's basically dup with #184
