### ISSUE TITLE
Can I use CLMS100Eth class on SICK LMS511 laser scanner?

### ISSUE THREAD

**Issue by gszh** [MRPT/mrpt#162]
Hello. I have a SICK LMS511 laser scanner. I tested it for CLMS100Eth class and it did not work.  I thought LMS series had the same structure. Isn't that right?

**Comment by jlblancoc** [comment]
Hi, 

Try with mrpt::hwdrivers::CSickLaserSerial, which works with the LMS 2XX series. 

Anyway, we haven't tested that model, so take a look at SICK's communication reference and check whether the protocol is more similar to LMS 2XX series or LMS 100. 
Cheers.

**Comment by gszh** [comment]
Thank you very much. I will give it a check. :-D
