### ISSUE TITLE
Assembler Error Message

### ISSUE THREAD

**Issue by majorpr13** [MRPT/mrpt#166]
When downloading and attempting to build the latest MRPT, I get an error in the assembler message such as 

/tmp/cckfgyj0.s: Assembler messages:
/tmp/cckfgyj0.s:2953: Error: no such instruction: `vfmadd312sd (%rsp),%xmm12,%xmm12'
/tmp/cckfgyj0.s:2963: Error: no such instruction: `vfmadd312sd (%rsp),%xmm13,%xmm13'
/tmp/cckfgyj0.s:2974: Error: no such instruction: `vfmadd312sd (%rsp),%xmm14,%xmm14'
make[2]: *** [libs/base/CMakeFiles/mrpt-base.dir/src/bayes/CParticleFilter.cpp.o] Error 1
make[1]: *** [libs/base/CMakeFiles/mrpt-base.dir/all] Error 2
make: *** [all] Error 2

Any thoughts as to the problem with this? I am currently running Ubuntu 12.04 on an Intel I5 64 bit.

**Comment by jlblancoc** [comment]
Really weird... 

See the proposed solution here: https://github.com/uzh-rpg/rpg_svo/issues/7

It seems you must disable the "optimize native" flag from MRPT CMake options (enable advanced variables in cmake-gui or ccmake to see all the flags).
