### ISSUE TITLE
[mrpt::synch] Create lightweight (non-Boost) shared/unique/upgradable (read/write) locks

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#171]
See: http://stackoverflow.com/a/244376/1631514

**Comment by jolting** [comment]
unique locks are already supported by c++11
http://en.cppreference.com/w/cpp/thread/unique_lock

shared locks are supported by c++14 compilers. This might be a problem until c++14 is ubiquitous.
http://en.cppreference.com/w/cpp/thread/shared_lock

Unfortunately, upgradeable locks aren't supported, but
It's worth reading:
https://isocpp.org/blog/2013/04/n3659-shared-locking
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3568.html

Here is Howard's public domain version of an upgradeable lock if you need one.
https://github.com/HowardHinnant/upgrade_mutex

**Comment by jlblancoc** [comment]
Again, thanks for the pointers!
The creation of non-C++11, non-boost classes in MRPT is intended to serve as a workaround until we definitively enforce the use of C++11/14 in MRPT 2.0.0 (See also: issue #66 )

**Comment by jlblancoc** [comment]
Since the current codebase does not make use of these features, I think that it makes more sense to just drop this topic for "milestone 1.5.0" and just use native C++11/14 classes in "milestone 2.0.0". 

So: closing this ticket.

**Comment by jolting** [comment]
Agreed
