### ISSUE TITLE
raw-grabber ust20lx

### ISSUE THREAD

**Issue by ricoliveira** [MRPT/mrpt#180]
Thread ends asking for a value COM_port_WIN, using the config file https://github.com/MRPT/mrpt/blob/master/share/mrpt/config_files/rawlog-grabber/hokuyo_UXM.ini.

This is ethernet, not usb...

 =============== MRPT EXCEPTION =============
mrpt::utils::CConfigFile::readString, line 161:
Value 'COM_port_WIN' not found in section 'LASER_2D' of file 'hokuyo_UXM.ini' an
d failIfNotFound=true.
mrpt::utils::CConfigFile::readString, line 171:
mrpt::hwdrivers::CGenericSensor::loadConfig, line 173:

**Comment by jlblancoc** [comment]
I've had a Hokuyo UST awaiting for testing on my desktop for one month... just test it, it should be fixed now! ;-) Thanks for reporting.
