### ISSUE TITLE
Merge PbMap

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#197]
From @EduFdez fork.
TO DO: 
- [ ] Changelog: Describe what's new in PbMap
- [ ] Pull request, check that it builds with and without PCL.

**Comment by EduFdez** [comment]
I'm working on this, I didn't do the pull request before because some things were not stable yet, but I'm planning to do it soon!

**Comment by jlblancoc** [comment]
Hi @EduFdez , 
I intend to release 1.4.0 soon, so I'll move this to 1.4.1 for you to have plenty of more time for testing, ok? Cheers! ;-)

**Comment by jlblancoc** [comment]
Hi @EduFdez : Any news on this pull-request? 
Shall I do the pull-request with the code in your branch as is? Is it stable?

Saludos!

**Comment by jlblancoc** [comment]
Hi @EduFdez !
I'm closing this one for now. If you want to do the merge in the future, I guess it would require doing a git rebase and/or substantial manual conflict solving... let us know if that's the case and you need a hand.
