### ISSUE TITLE
rbpf-slam RO-SLAM sample ini files throw exception from unimplemented internal_computeObservationLikelihood function

### ISSUE THREAD

**Issue by prpsymbol** [MRPT/mrpt#214]
I am using the 64-bit binaries for Windows. Error:
 =============== MRPT EXCEPTION =============
mrpt::maps::CHeightGridMap2D::internal_computeObservationLikelihood, line 224:
Not implemented yet!
MapExecutor::run, line 54:

**Comment by jlblancoc** [comment]
Hi!
Duplicated of #205 

It has been already fixed in git master, see commit e579e94d83f25676cce743b702e8acded7554e35

Next release 1.4.0 will come with it fixed, hopefully to be published within days...

**Comment by prpsymbol** [comment]
Sorry for the duplication, and thank you! I will wait for the updated release.

-Paul
