### ISSUE TITLE
can't run the grid-matching application

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#217]
I tried to run the grid-matching application either manually or with the run_whole_experiment.sh script provided in the feature_benchmark.tar.gz file (http://www.mrpt.org/downloads/feature_benchmark.tar.gz) . For every match execution a PARSE ERROR is raised for the ax parameter as shown below:

```
PARSE ERROR: Argument: --Ax=-0.926

Couldn't find match for argument

Brief USAGE: 
grid-matching [--most-likely-only] [-s] [-n] [-g] [-v] [-L] [-O] [-P
<phi>] [-Y <y>] [-X <x>] [-N <rep.count>] [-l <sigma>]
[-p <sigma>] [-x <sigma>] [-i <icp_goodness.txt>] [-t]
[-a] [-3] [--out-dir <grid-matching_results>] [--aligner
<[amCorrelation|amRobustMatch|amModifiedRANSAC]>] [-c
<config.ini>] [-o <result_outfile>] [-2 <map2.simplemap>]
-1 <map1.simplemap> [-d] [-m] [--] [--version] [-h]

For complete USAGE and HELP type: 
grid-matching --help
```

Removing the --Ax=.. --Ay=.. parameters didn't solve the problem.

**Comment by jlblancoc** [comment]
Sorry for the problems... it seems the argument parser of `grid-matching` changed and we forgot to update that script. 

Please, try removing the `=` sign, e.g. 

        grid-matching --Ax -0.926 ....

FYI: [Here](https://github.com/MRPT/mrpt/blob/master/apps/grid-matching/grid-matching_main.cpp#L676) is the list of parameters definitions.
