### ISSUE TITLE
rawlog-grabber output log "peek: seek out of range", when grabber the NMEA data  of GPS

### ISSUE THREAD

**Issue by 9578577** [MRPT/mrpt#224]
Today , I found the rawlog-grabber always print the information "peek: seek out of range" in log.
when I use the rawlog-grabber to grabber the NMEA data of GPS.
The information would be shown when the rawlog file will more than 18MB.

So, I change the buffer size of GPS serial port to 0x20000, and modify the 48th line of parser_NMEA file
from "if (val=='\r' || val=='\n') {" to "if (val=='\n') {"

Now, It is normal.

**Comment by jlblancoc** [comment]
Thanks!
But that seems sort of a hack / workaround... 

I will investigate the issue in depth adding intensive unit tests around `peek()` and will notify the results here.

**Comment by jlblancoc** [comment]
@9578577 please, test it now after the lastest commit. It should be fixed...
