### ISSUE TITLE
CImage::loadFromFile setting img to NULL on OpenCV failure

### ISSUE THREAD

**Issue by jolting** [MRPT/mrpt#228]
Here's the offending line:
```c++
    return (NULL!= (img=cvLoadImage(fileName.c_str(),isColor) ));
```
This should probably be something like:
```c++
IplImage* tempImg=cvLoadImage(fileName.c_str(),isColor);
if(tempImg != NULL)
{
  img = tempImg;
  return true;
}
return false;
```
Most of the CImage routines assume that img is never NULL, so this is bad.
Alternatively, img could be set to the default 1x1 pixel image that CImage defaults to, but I think this is unnecessary.

**Comment by jlblancoc** [comment]
Thanks @jolting !
