### ISSUE TITLE
Error: Kinect_3D_SLAM LINK1104 w/ Kinect V2

### ISSUE THREAD

**Issue by T3dward** [MRPT/mrpt#257]
When I am trying to build Kinect 3D slam, following error comes out.
I am using KINECT V2.

1> All outputs are up-to-date
1>ManifestResourceCompile:
1> All outputs are up-to-date
1>LINK : fatal error LNK1104: cannot open file 'libmrpt-hwdrivers140-dbg.lib'

**Comment by jolting** [comment]
This might be obvious, but make sure BUILD_HWDRIVERS is set.
In your build directory you should have:
$(BUILD)/lib/Debug/libmrpt-hwdrivers140-dbg.lib

Please list the contents of the Debug directory.

**Comment by jlblancoc** [comment]
Closing for lack of feedback after >1 month.
