### ISSUE TITLE
simul-beacon and negative sensed distances

### ISSUE THREAD

**Issue by prpsymbol** [MRPT/mrpt#270]
Hi JL,

Still working (on and eff) with simul-beacon and rbpf-SLAM and making progress. Looking a little deeper at the simul-beacon results, I see that CBeaconMap::simulateBeaconReadings can generate negative values for the sensed distance. Real beacon systems will not do that, however, and ranges always have a minimum value of zero. I am thinking the sensed distance returned should be the absolute value of the noise perturbed range. What do you think?

**Comment by jlblancoc** [comment]
Mmm... good point. Normally the noise should be orders of magnitude smaller than the sensed range, but it's true that for really small distances that may happen. I see two solutions to this: 
* Your idea: taking the abs() of ranges + noise. That should definitively go there. 
* But also, it might be interesting to add an optional minimum range to reflect the limitations of real ranging devices, which always have a minimum range. By setting the default value to 0 the behavior will be backwards compatible. 

If you are interested in this and want to give it a try, I'll be happy of accepting a Pull-Request with these features!
