### ISSUE TITLE
Changing rbpf-SLAM demo  background color

### ISSUE THREAD

**Issue by prpsymbol** [MRPT/mrpt#272]
Hi JL,

Silly question, but how can I change the default grey background color of the rbpf-SLAM demo program? I am grabbing screen shots, but the dark grey prints rather poorly.

-Paul

**Comment by jlblancoc** [comment]
Hi, 

It's not obvious, admittedly...

```
mrpt::opengl::COpenGLScenePtr &scene = win.get3DSceneAndLock();
scene->getViewport("main")->setCustomBackgroundColor( TColorf(0.8f,0.8f,0.8f)); // RGB color
win.unlockAccess3DScene();
win.repaint();
```

Cheers.
