### ISSUE TITLE
graphslam-engine: Add nodes in the graph in an adaptive fashion

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#314]
@jlblancoc, @EduFdez
**Goal:** : Implement a node registration decider class that adds nodes to the graph adaptively. This goes hand-in-hand with (node-reduction scheme)

Note: Issue goes hand-in-hand with [Node Reduction issue](https://github.com/MRPT/mrpt/issues/315)
[Proposed Label] Enhancement

**Comment by jlblancoc** [comment]
I'm afraid this one is outdated by now... :-( 
Closing it...
