### ISSUE TITLE
graphslam-engine: Cleanup and Fix code bugs

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#318]
@jlblancoc, @EduFdez 

Final product should address the following:
- [x] Remove hwdrivers lib/app dependency
- [x] Cut down on the size of graphslam-engine-demos directory
- [x] Reduce size of application-page, add details about library implementation, application usage in a seperate external guide
- [ ] Investigate trajectory zig-zags
- [ ] Fix RGB-D dataset handling
- [ ] Deal with synchronization issue when optimize_on_second_thread flag is True
- [x] Modify the structure of library and application files. Have all the methods defined in the library files and just make the necessary calls from the application - Split the [execGraphSlamEngine](https://github.com/MRPT/mrpt/blob/graphslam-devel/libs/graphslam/include/mrpt/graphslam/CGraphSlamEngine_impl.h#L378) method

**Comment by jlblancoc** [comment]
I'm afraid this one is outdated by now... :-( 
Closing it...
