### ISSUE TITLE
2060907 mrpt origin/master make error

### ISSUE THREAD

**Issue by 9578577** [MRPT/mrpt#323]
/home/linux/mrpt/python/src/pnp_bindings.cpp:4:32: fatal error: numpy/arrayobject.h: No such file or directory
compilation terminated.
python/CMakeFiles/pymrpt.dir/build.make:326: recipe for target 'python/CMakeFiles/pymrpt.dir/src/pnp_bindings.cpp.o' failed
make[2]: *** [python/CMakeFiles/pymrpt.dir/src/pnp_bindings.cpp.o] Error 1
CMakeFiles/Makefile2:7310: recipe for target 'python/CMakeFiles/pymrpt.dir/all' failed
make[1]: *** [python/CMakeFiles/pymrpt.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jolting** [comment]
Please post more info about what you're trying to do. 

The python bindings require numpy now.

If on ubuntu:
sudo apt-get install python-numpy

Alternatively, install numpy with pip.

**Comment by jlblancoc** [comment]
Thanks for the note, @jolting !
I've updated the [wiki instructions](https://github.com/MRPT/mrpt/wiki/PythonBindings) on Python.
