### ISSUE TITLE
PnP Class for Windows 

### ISSUE THREAD

**Issue by mangi020** [MRPT/mrpt#335]

**Comment by jlblancoc** [comment]
Hi Chandra,

If you refer to the commit in which I mentioned you, that was a small error
and should be already fixed with my commit.

So, what is this issue ticket for? Should it be closed now?

Cheers,

**Comment by mangi020** [comment]
Sry I thought

**Comment by mangi020** [comment]
Sry, I thought there was some big problem or so. Thanks
