### ISSUE TITLE
Insertion of observation into CPointMap not thread safe.

### ISSUE THREAD

**Issue by jolting** [MRPT/mrpt#338]
https://github.com/MRPT/mrpt/blame/master/libs/maps/src/maps/CPointsMap_crtp_common.h#L143

Calling reserve on a vector like this often can cause the entire vector to get reallocated and moved. It's not guaranteed to simply grow the vector in-place. Therefore, this operation is not thread safe. Also, the non-trivial case of the reserve may also increase overhead.

We caught this one with -fsanitize=address. It went unnoticed for quite a while.

I think the intuitive thing is to treat observations as const when inserting them, but I haven't considered how much effort it will be to add the type qualifiers.

**Comment by jlblancoc** [comment]
> We caught this one with -fsanitize=address. It went unnoticed for quite a while.

wow!!  What a discovery: a built-in valgrind, so cool...

> Calling reserve on a vector like this often can cause the entire vector to get reallocated and moved. It's not guaranteed to simply grow the vector in-place. Therefore, this operation is not thread safe. Also, the non-trivial case of the reserve may also increase overhead.

Absolutely agree... I can think of a number of alternative ways to fix this, will come back later with one of them. 

Thanks for the research.

**Comment by jlblancoc** [comment]
Please, read https://github.com/MRPT/mrpt/pull/340 for a discussion of the applied changes...
