### ISSUE TITLE
Memory leak in CStream when exception is thrown

### ISSUE THREAD

**Issue by jolting** [MRPT/mrpt#342]
If an exception is thrown in MRPT while attemping to read an MRPT log you will get a memory leak.

```
 =============== MRPT EXCEPTION =============
std::size_t mrpt::utils::CStream::ReadBuffer(void*, std::size_t), line 53:
(EOF?) Cannot read requested number of bytes from stream
Exception while parsing typed object 'CObservation2DRangeScan' from stream!

virtual void mrpt::obs::CSensoryFrame::readFromStream(mrpt::utils::CStream&, int                                                                                                                ), line 146:
Exception while parsing typed object 'CSensoryFrame' from stream!
```

https://github.com/MRPT/mrpt/blob/master/libs/base/src/utils/CStream.cpp#L431

An object is created in CStream::internal_ReadObject, but it's not immediately assigned to a smart pointer, so if an exception is thrown on `obj->readFromStream( *this, (int)version );`  and it's not an existing object then the `obj` won't get freed when the stack unwinds.

The quick fix is to immediately assign it to a smart pointer.

**Comment by jlblancoc** [comment]
Great! Thanks. 

It should be fixed with the commit above. I'll try the sanitizer myself, but please check if the leak has effectively gone away.
