### ISSUE TITLE
OccupyGrid2D map problem : how to fit edge of obstacle such as wall to be solid line ?

### ISSUE THREAD

**Issue by simplePig** [MRPT/mrpt#351]
I have got a grid map file filled with sparse and scattered point cloud generated from 2D laser lidar , now i want to fit edge of obstacle such as wall to be solid line and change every cell value to be threshold within 0,1 .
In other words , i wan to the map only has not mediate value but tow colors black(0) and white(1) and not any scattered point cloud but all solid line .
Who can tell me how to solve the problem ? which API ？ I can not find an effective algorithm ...

**Comment by jlblancoc** [comment]
Hi, 

To have only (0,1) values in the map, try increasing to 0.99 the value of `maxOccupancyUpdateCertainty` in the gridmap's `insertionOptions` member.
