### ISSUE TITLE
Warning messages on gcc 4.6.3

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#360]
@mangi020 @jlblancoc 

Just wanted to let you know that expressions like [this](https://github.com/MRPT/mrpt/blob/master/python/include/bindings.h#L88) generate a warning for gcc, g++ 4.6.3:

"warning: comparison of unsigned expression always >= 0 is always true"

There are multiple warning messages like this in the *_bindings files.
I suppose it's not a big issue, since the check is but they are warnings nonetheless. :)

**Comment by mcprakash** [comment]
@bergercookie 
 Will take a look ASAP

**Comment by jlblancoc** [comment]
Thanks, @bergercookie , these must be addressed.

**Comment by jlblancoc** [comment]
I fixed the warnings, but couldn't reproduce them with GCC 5.4....
