### ISSUE TITLE
mrpt compilation error: 'class wxEvtHandler' has no member named 'CallAfter'

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#372]
Here is the full error report: [error.txt](https://github.com/MRPT/mrpt/files/586750/error.txt)

Compiler: gcc
Platform: Ubuntu

**Comment by jolting** [comment]
Please use wx 3.0 it is available as far back as trusty. 2.8 doesn't have it.

**Comment by bergercookie** [comment]
Ah, that explains. Thanks @jolting
