### ISSUE TITLE
No localization in ICP

### ISSUE THREAD

**Issue by NimeniAltuQ** [MRPT/mrpt#395]
Hello! I am using ICP with a RPLidar, it shows me a map but this map is not like the maps in the videos. The map changes if the robot is moving, but i need the map to remain static and move just the robot inside map. Can you help me?

**Comment by NimeniAltuQ** [comment]
Also it says "new pose extrapolation failed"

**Comment by jlblancoc** [comment]
Have you tried to grab a .rawlog with your RPlidar data and process it with icp-slam? 

The message on "new pose extrapolation failed" is not critical. Actually it's expected since it means that we don't have odometry and there are no velocities to extrapolate! ;-)
