### ISSUE TITLE
build failed cannot find -lwx_gtk2_gl-2.8 

### ISSUE THREAD

**Issue by Grillen80** [MRPT/mrpt#402]
Hello,
my build runs in an error with the following message:

_[ 16%] Linking CXX shared library ../../lib/libmrpt-base.so
/usr/bin/ld: cannot find -lwx_gtk2_gl-2.8
collect2: error: ld returned 1 exit status_

I think that I set up wx 2.8 and gtk2 properly. This error drives me nuts....

**Comment by jlblancoc** [comment]
Hi, 

I'll close this ticket if no more info is provided... OS version, which version of MRPT is being built, etc.
