### ISSUE TITLE
A bug in CPointsMap.cpp?

### ISSUE THREAD

**Issue by ygzhangsoya** [MRPT/mrpt#435]
In [CPointsMap.cpp](https://github.com/MRPT/mrpt/blob/master/libs/maps/src/maps/CPointsMap.cpp)

line 562  `if ( bestMatchForThisMap[it->this_idx] != &(*it) )`: I think it should be `==` instead of `!=`. Is it a bug?

```cpp
   558         //   2) Go again through the list of correspondences and remove those
   559         //       who are not the best one for their corresponding global map.
   560         for (it=_correspondences.begin();it!=_correspondences.end(); ++it)
   561         {
   562             if ( bestMatchForThisMap[it->this_idx] != &(*it) )
   563                 correspondences.push_back( *it );                   // Add to the output
   564         }
```

**Comment by jlblancoc** [comment]
Thanks @ygzhangsoya !! 

I'm afraid you're right... please, review my patch above. It basically fixes as you said, by the way updating the coding style to C++11. 

Apparently the bug has been there for... more than 8 years. Please, let us know if you a chance to do some testing with that "unique correspondences filter" enabled, to see if that seems to work better now. 

Cheers

**Comment by ygzhangsoya** [comment]
Thanks for the prompt reply. The patch looks good! Thank you for maintaining the library. It's very helpful. 

I think I'll play with it and will let you know how it works now. 

Cheers

**Comment by ygzhangsoya** [comment]
Just notice the same bug in line 1204-1208 in [CPointsMap.cpp](https://github.com/MRPT/mrpt/blob/master/libs/maps/src/maps/CPointsMap.cpp). You may want to update it as well.

**Comment by jlblancoc** [comment]
Thanks again! I refactored the duplicated code, as can be seen in the commit above.
I tested ICP with `onlyUniqueRobust`=true  and seems to work great.
