### ISSUE TITLE
Add debugging symbols to mrpt library for external project use - source compilation

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#482]
@jlblancoc,  loosely based on @alexge233's issue [here](https://github.com/MRPT/mrpt/issues/479), I encountered the same error log when I tried adding debugging symbols to the mrpt-graphslam library.

I compiled mrpt source using the CMAKE_BUILD_TYPE=Debug flag so that I could use the debugger in the mrpt_slam/mrpt_graphslam_2d application (which apparently made use of the mrpt-graphslam library).

**Comment by jolting** [comment]
https://github.com/MRPT/mrpt/issues/211

I propose don't append -dbg on Linux.

**Comment by bergercookie** [comment]
I think I've come to this issue again. However if you compile with the DONT_USE_DEBUG_LIBS flag, the debugger can't inspect any part of the program related to the MRPT library that you are using (stack trace, lines, variable contents etc). Isn't this the case? I was hoping for a way of getting the line that the program crashes, even if that is in mrpt-graphslam lines..

**Comment by jolting** [comment]
No. If compiled with debug symbols it will use them. 

The dbg package just installs it in a place where gdb can find the symbols. They are stripped out of the library and stuck in a seperate folder, so the library name should stay the same regardless of using debug symbols.

**Comment by jlblancoc** [comment]
> #211
>
> I propose don't append -dbg on Linux.

I think it's time to surrender... you're right: this convention makes
sense and is really useful in Windows, but seems a permanent source of
confusion in Linux.

**Comment by jlblancoc** [comment]
Closed after merge of #484

**Comment by jolting** [comment]
I think windows would be better if it had some rpath analog. It's very useful to have local builds around and embed rpath in the binary, so you don't have to manually specify library search paths. 

Windows is a bit unruly. I've had to once or twice manually gather dlls to run my apps.it makes sense on windows to add -dbg for this reason.
