### ISSUE TITLE
Lintian error: copyright issue

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#522]
1.4.0 (and master) raises [this](https://lintian.debian.org/tags/license-problem-convert-utf-code.html) Debian lintian error.

Looks like we must modify SimpleINI to remove the UTF part which, anyway, was seldom (?) used by anyone, right?

Adding to 1.5.0 milestone since it's a stopper for updating MRPT packages in Debian.

**Comment by jolting** [comment]
If this needs to be resurrected in the future, maybe just use libicu. I think they took over the reference implementation. Maybe we can find a use for emojis in our INI files. 😄

**Comment by jlblancoc** [comment]
😂👍
