### ISSUE TITLE
GraphSLAM docs error

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#540]
While building the docs:

> Latexmk: 'pdflatex': source file 'graphslam-engine-guide.nls' doesn't exist.

A missing file to be added to Git, @bergercookie ?

PS: I know this is not the best week for you to get out of focus... so don't worry, take the time you need to look at this, no rush at all! ;-)

**Comment by bergercookie** [comment]
This should be closed via https://github.com/MRPT/mrpt/commit/3a103b33f964089dd875b5186a932a472530db9c, right?
