### ISSUE TITLE
Error compilación 

### ISSUE THREAD

**Issue by andres-ss25** [MRPT/mrpt#558]
Hello everyone

I would like to please help me, I have Ubuntu 16.04 LTS, downloaded and installed MRPT 1.5.0 from the source code, compiled without any problem. But when compiling a modification of the pbmap-tutorial example I get an error when linking a library.
![error](https://user-images.githubusercontent.com/5648275/27991057-6f33a846-6430-11e7-950d-2712e5c79396.png)

**Comment by jlblancoc** [comment]
¡Hola Andrés! 

Does the error also happen with the **unmodified** version of the example? 
Could you please post in a ZIP file your exact CMakeLists and .cpp files so we can replicate the issue?

**Comment by andres-ss25** [comment]
Hello jose
Thanks for the prompt response. Being more detailed, I downloaded compiled and installed with sudo make install.
The example is the same tutorial-pbmap-construction.cpp.  I took it from the samples folder to desktop and  i wish compile it and test it there. Attachment .cpp and CMakeLists.txtx
[pbmap-tutorials.zip](https://github.com/MRPT/mrpt/files/1134389/pbmap-tutorials.zip)

**Comment by jolting** [comment]
You're missing a space in your CMakeLists.txt file.
```
-TARGET_LINK_LIBRARIES(mrpt_pbmap-construction ${MRPT_LIBS}${PCL_LIBRARIES})
+TARGET_LINK_LIBRARIES(mrpt_pbmap-construction ${MRPT_LIBS} ${PCL_LIBRARIES})
```

**Comment by andres-ss25** [comment]
Hello

Jose and Joltin

Thanks for your prompt response, I really feel sorry for the mistake in the CMakeLists edition. I will pay more attention.
