### ISSUE TITLE
CDisplayWindow3D crashes after Qt-related refactoring

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#571]
How to reproduce: 

Build MRPT samples, execute: 

```
gdb samples/opengl_objects_demo/opengl_objects_demo
run
(upon crash)
bt
```

Output:

```
Thread 2 "opengl_objects_" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe47c0700 (LWP 2106)]
0x00007ffff7bb0abd in mrpt::gui::CMyGLCanvasBase::OnMouseMove(wxMouseEvent&) () from /home/jlblanco/code/mrpt/build/lib/libmrpt-gui.so.1.9
(gdb) bt
#0  0x00007ffff7bb0abd in mrpt::gui::CMyGLCanvasBase::OnMouseMove(wxMouseEvent&) () from /home/jlblanco/code/mrpt/build/lib/libmrpt-gui.so.1.9
```

Any quick idea on the cause of the problem, @LisGein ?

**Comment by LisGein** [comment]
No, but it crashed on the line 
136 this->SetFocus();

**Comment by LisGein** [comment]
I am checking it.

**Comment by LisGein** [comment]
I found several problems:
* I don't know how and why, but 
in the constructor sets m_gl_context as nullptr
after calls OnWindowCreation and "if (!m_gl_context)" == false. 

* This is a second problem:
![image](https://user-images.githubusercontent.com/8298625/28670901-6606212e-72e3-11e7-97fd-7530e0f52f98.png)

**Comment by jlblancoc** [comment]
Thanks!

I recall adding a SetFocus in each event of the mouse as a workaround to
some other issues... I can't test it now, but probably an "if" that checks
if the window is not nullptr (or something alike...) before doing the
SetFocus would help. Or even the SetFocus could be commented out to confirm
it's the cause...
