### ISSUE TITLE
Any plans to release 1.5 debian packages?

### ISSUE THREAD

**Issue by corot** [MRPT/mrpt#572]
@jlblancoc ,  debian web is calling for your attention:   :grin:
https://packages.qa.debian.org/m/mrpt.html

**Comment by jlblancoc** [comment]
Thanks! We had some problems, but I'm precisely today talking to mentors
and the ball is rolling again, very soon we'll have a new pkg! ... and,
probably, the usual cascade of unexpected build errors in rare
architectures 😂😂

Thanks for the kind reminder ;-)

**Comment by jlblancoc** [comment]
The latest attempt (which might be uploaded to Debian soon) is [here](https://mentors.debian.net/package/mrpt) just in case you are curious...

**Comment by jlblancoc** [comment]
[Here](https://ftp-master.debian.org/new/mrpt_1:1.5.3-1.html) is it in the [NEW](https://wiki.debian.org/NewQueue) queue, due to the minor version change... waiting for approval.
