### ISSUE TITLE
Add "nodelets" for in-process efficient communications

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#585]
* [x] Add @jolting 's [idea](https://github.com/MRPT/mrpt/issues/66#issuecomment-288636679) to the new module mrpt-comms.
* [x] Write examples.
* [x] Write unit tests.

**Comment by jlblancoc** [comment]
This is finally in progress!  :+1:  
Changed the name "node" to "topic" since, I think, it's more accurate...
And created a simple example (subscriber callback not being called yet for some reason, but not looked much to this yet).

**Comment by jolting** [comment]
I forgot about this one. We have c++17 on now.

**Comment by jolting** [comment]
I think a filter class might be cool. On construction it subscribes and on destruction it unsubscribes.
Also a method of instantiating filters based on a yaml file.

**Comment by jlblancoc** [comment]
And we'll end up with a mini ROS2 XDD

> I think a filter class might be cool. 

👍 yeap!

**Comment by jolting** [comment]
WIthout being encumbered by interprocess communication. At least initially.

**Comment by jlblancoc** [comment]
This one was already done time ago: 240f9d4317123498dc223b11aa2a831d0cf083a6
Closing.
