### ISSUE TITLE
OpenCV2 dependency

### ISSUE THREAD

**Issue by jthsieh** [MRPT/mrpt#597]
System: Ubuntu 16.04

I am trying to compile another project that depends on MRPT. I installed MRPT with
`sudo apt-get install libmrpt-dev mrpt-apps`
To verify the installation, the command `ls /usr/lib/x86_64-linux-gnu/ | grep mrpt` shows a lot of packages: `libmrpt-***.so.1.3`.

However, when compiling my original project, I get this warning:
`warning: libopencv_core.so.2.4, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmrpt-base.so, may conflict with libopencv_core.so.3.2`

It seems that MRPT1.3 has the old OpenCV2.4 as a dependency. My code compiles, but the binary doesn't work, `cv::imread()` keeps returning an empty matrix. The command `ldd my_binary | grep opencv` lists both `libopencv_***.so.3.2` AND `libopencv_***.so.2.4` as dependencies. This is probably why it doesn't work.

So, I tried installing a newer version of MRPT. I removed the packages and ran the following commands:
`sudo add-apt-repository ppa:joseluisblancoc/mrpt-1.5`
`sudo apt-get update`
`sudo apt-get install libmrpt-dev mrpt-apps`

This installs MRPT 1.5. The `ls /usr/lib/x86_64-linux-gnu/ | grep mrpt` command shows the correct packages `libmrpt-***.so.1.5`.
However, the same warning still exists, and the binary still depends on both versions of OpenCV.

I am currently trying to build MRPT from source, but I got this error and haven't solved it:
`/usr/bin/ld: CMakeFiles/rawlog-grabber.dir/rawloggrabber_main.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'`
`//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`
`apps/rawlog-grabber/CMakeFiles/rawlog-grabber.dir/build.make:176: recipe for target 'bin/rawlog-grabber' failed`
`...`

So, is there a version of MRPT that depends on OpenCV3?

**Comment by jlblancoc** [comment]
Hi, 

In this case, where you have a version of OpenCV that is more modern than the default version in Ubuntu, I can only recommend you to build MRPT from sources. 
Note that you should first uninstall all MRPT Debian packages, and that you DON'T need to run `make install` after building. Just set MRPT_DIR to the proper MRPT compilation directory in your app.
