### ISSUE TITLE
RFC: refactoring of mrpt-base

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#615]
Motivated by:
* [this](https://github.com/MRPT/mrpt/commit/3aec720fe5205bfe5d974580a29360c923c523e6#commitcomment-25702556) MSCV linker limitation.
* because it's true that `mrpt-base` is really large and includes too many functionalities,  and
* because of the potential utility of having many smaller `libmrpt-XXX-dev` packages (see #588 )

we want to split mrpt-base into a more logical set of smaller modules.

WIP happens in the [dev-module-refactor](https://github.com/MRPT/mrpt/tree/dev-module-refactor) branch.

New list of mrpt modules/libraries (check box = it's "done", builds, and passes tests).
* [x] `mrpt-config`: NEW. Configuration files, etc.
* [x] `mrpt-containers`: NEW.  All container classes.
* [x] `mrpt-core`: NEW. Mainly preprocessor macros and bottom-line, basic functionality; e.g. `mrpt::format()`. Should have a ridiculously small footprint since will be included in all other modules.
* [x] `mrpt-expr`: NEW. exposes `exprtk.hpp`  **and** also the precompiled version in `mrpt::expr::CRuntimeCompiledExpression`.
* [x] `mrpt-io`: NEW. (streams, files). 
* [x] `mrpt-math`: NEW. all math classes (idea needs further refining)
* [x] `mrpt-random`: NEW. 
* [x] `mrpt-serialization`: NEW. CSerializable and related stuff. Refactored to make it stream independent (i.e. could be used with std::ostream).
* [x] `mrpt-system`: contents of namespace `mrpt-system`. 
* [x] `mrpt-typemeta`: NEW. 

Old libs (mark when fixed after the refactoring):
* [x] `mrpt-base`: Add as a meta-lib for backwards compat?
* [x] `mrpt-bayes`: pending
* [x] `mrpt-comms`: pending
* [x] `mrpt-detectors`: pending
* [x] `mrpt-graphs`: pending
* [x] `mrpt-graphslam`: pending
* [x] `mrpt-gui`: pending
* [x] `mrpt-hmtslam`: pending
* [x] `mrpt-hwdrivers`: pending
* [x] `mrpt-kinematics`: pending
* [x] `mrpt-maps`: pending
* [x] `mrpt-nav`: pending
* [x] `mrpt-obs`: pending
* [x] `mrpt-opengl`: pending
* [x] `mrpt-slam`: pending
* [x] `mrpt-tfest`: pending
* [x] `mrpt-topography`: pending
* [x] `mrpt-vision`:   pending

Others:
* [x] Use libtclap-dev if available. Download sources if not found in Windows, recommend apt-get install in Ubuntu.
* [x] MRPT_DECLARE_TTYPENAME -> in-class alternative with new typemeta macro.  
* [x] TEnumType -> new macros for better readability
* [x] Rename & sort examples.

**Comment by jolting** [comment]
I wonder how many symbols belong to eigen. I think those are exported when statically linking mrpt dlls against eigen. That might be a huge source of symbols.

**Comment by jlblancoc** [comment]
> I wonder how many symbols belong to eigen. 

Another good reason to experiment with implementing #496 in this new branch... ;-)

**Comment by jlblancoc** [comment]
FYI: The latest graph of module deps for this branch is [here](http://mrpt.ual.es/reference/dev-module-refactor/dot_inline_dotgraph_2.png) (rebuilt after each commit):

![deps](http://mrpt.ual.es/reference/dev-module-refactor/dot_inline_dotgraph_2.png)

**Comment by jlblancoc** [comment]
I intend to make mrpt-random, and the new modules for "typenames" (RTTI) and serialization, as independent of MRPT as possible. Ideally, not even depending on "mrpt-core", so anyway can install them via `apt install libmrpt-xxx-dev` and use as standalone libs.
That's the intention, at least... (sigh)

**Comment by jlblancoc** [comment]
BTW:  current approach in mrpt-typemeta, together with the yet-to-be mrpt-serialization, will finally solve #14

**Comment by jlblancoc** [comment]
Updated the first comment with a list of checkboxes to reflect progress in this task.

**Comment by jlblancoc** [comment]
Temporarily created branch [master-ref-point-before-refactoring](https://github.com/MRPT/mrpt/tree/master-ref-point-before-refactoring) based on master, with shippable all green, as a reference point to compare build times after the refactoring of this and the #496 issues, to quantify the gain of the changes.

**Comment by jlblancoc** [comment]
This huge task is now 100% done, at the level of mrpt libraries and applications... Yay!
I'm opening a PR to integrate the huge number of changes in master, then will continue with the few remaining colateral issues: fixing examples & documentation, mainly.

**Comment by jlblancoc** [comment]
3 months later... this big one is done after #648, Yay!
