### ISSUE TITLE
Run the icp-slam-demo have a exception

### ISSUE THREAD

**Issue by PDFCS** [MRPT/mrpt#635]
I run icp-slam demo under Ubuntu，I use the following command：
cd MRPT/share/mrpt/config_files/icp-slam/
icp-slam_demo_classic.ini YOUR_DATASET.rawlog
the rawlog file is “2007-05MAY-17_SENA_Floor2.3_1laser.rawlog” in https://www.mrpt.org/robotics_datasets
but when I use the  icp-slam demo，have a following issue：
 =============== MRPT EXCEPTION =============
void mrpt::slam::CMetricMapBuilderICP::processObservation(const mrpt::obs::CObservationPtr&), line 136:
Assert condition failed: odo->timestamp!=INVALID_TIMESTAMP
 /build/mrpt-6QpeJH/mrpt-1.5.6~snapshot20180118-git-850da4f3-trusty/libs/slam/src/slam/CMetricMapBuilderICP.cpp:372: In `void mrpt::slam::CMetricMapBuilderICP::processObservation(const mrpt::obs::CObservationPtr&)`
 /build/mrpt-6QpeJH/mrpt-1.5.6~snapshot20180118-git-850da4f3-trusty/apps/icp-slam/icp-slam_main.cpp:485: In `void MapBuilding_ICP(const string&, const string&)`

**Comment by jlblancoc** [comment]
Hi, 

If I recall it right, that specific dataset was so old that the timestamp field was not present, so it's loaded as INVALID_TIMESTAMP. 

You can fix it by loading the .rawlog into RawLogViewer, then use the menu: Sensors -> Odometry -> Regenerate invalid timestamps, then save it as a restored .rawlog file.
