### ISSUE TITLE
Sophus license is missing

### ISSUE THREAD

**Issue by richmattes** [MRPT/mrpt#644]
The bundled Sophus code is licensed under the MIT license, which stipulates that the copyright notice and permissions shall be included with all copies or substantial portions of the software.

Please include a copy of the Sophus LICENSE.txt with the Sophus source.

**Comment by jolting** [comment]
I added to LICENSE file to the sophus folder.
Just a reminder for myself. The debian packaging needs to be updated too.

**Comment by jolting** [comment]
@richmattes Thanks for bringing this to my attention. I take licensing very seriously.

I've added the LICENSE.txt file to the 1.5 and 2.0(master) branches and updated the debian copyright files to provide proper attribution. Our next releases should be compliant with the licensing requirement.

**Comment by jlblancoc** [comment]
Thanks @richmattes for noticing and reporting!

**Comment by richmattes** [comment]
You're welcome, glad to help!
