### ISSUE TITLE
octomap debug 'd' decorator is causing problems on Linux build.

### ISSUE THREAD

**Issue by jolting** [MRPT/mrpt#652]
If I get rid of `$<$<CONFIG:Debug>:d>` it seems to work alright.

https://github.com/MRPT/mrpt/blob/e669d7af88d8385ae583a43cf8992351c4cb5936/cmakemodules/script_octomap.cmake#L55

I guess this is something used on Windows that is not compatible with Linux.

**Comment by jolting** [comment]
This is fixed in #654

**Comment by jlblancoc** [comment]
Great, thanks!
