### ISSUE TITLE
Not able to build since #615

### ISSUE THREAD

**Issue by JuniorIng** [MRPT/mrpt#662]
Hi,
I am trying to build Joint-VO-SF from https://github.com/MarianoJT88/Joint-VO-SF and receive the build error "CMake Error at /usr/share/mrpt/MRPTConfig.cmake:223 (MESSAGE):
  ERROR: MRPT_FIND_COMPONENTS contains 'mrpt-base', not built in mrpt (built
  ones:
"
As i just read in #615 that this lib is not further included I think this might be the problem. Is there a way to include it for backwards compatibility? Or might there be another solution?
Thank you so much,
Jan

**Comment by jlblancoc** [comment]
Hi,

Please, feel free of opening a PR in @MarianoJT88 's repo to address this issue. 
Ideally, one could make the code compatible with both version series of mrpt 1.5 and 2.0, by using cmake code fragments like this:

https://github.com/mrpt-ros-pkg/mrpt_slam/blob/348822458fe3f95af600a742a8f2badfb413fd98/mrpt_ekf_slam_2d/CMakeLists.txt#L21-L27

If you just want to run that code, you could stay with the maintenance branch mrpt 1.5, but upgrading Mariano's code would be great ;-)
