### ISSUE TITLE
Make pf-localization work with either SE(2) or SE(3) poses

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#669]
Right now, it's hard wired to work with mrpt::slam::CMonteCarloLocalization2D, but it could be refactored (templatized) so it could work with mrpt::slam::CMonteCarloLocalization3D as well. 
The choice should be done via a config file parameter.

**Comment by jolting** [comment]
Nice. How well does it perform on a drone?

**Comment by jlblancoc** [comment]
Hmm... interesting :-) 
Haven't tested it. Only tested for now with a ground vehicle + VLP-16. I have an "old" dataset of a dron with a velodyne onboard, could give it a try....
