### ISSUE TITLE
Can I use dlls from the precompiled binaries in VS17?

### ISSUE THREAD

**Issue by pettaa123** [MRPT/mrpt#692]
Hi, I want to compile the test.cpp from example1 in VS17. I included the following directories of the installation from the prebuild binaries:
mrpt-1.5.5\include\mrpt\mrpt-config
mrpt-1.5.5\libs\base\include
Linker:
mrpt-1.5.5\bin
libmrpt-base155_msvc140_x64.dll

After starting compiling I get an error saying: corrupted file libmrpt-base155_msvc140_x64.dll

Is it possibile to use the dlls from the prebuild binaries for my own VisualStudio17 projects?

**Comment by jolting** [comment]
It might be possible, but I wouldn't recommend it. Also, you should link the .lib file and not the .dll file.

Are you using cmake?

**Comment by pettaa123** [comment]
Hi, my bad. Compiling was not the problem, the .exe couldn't find the dll when starting it. Adding mrpt/bin/ to PATH solved my issue. I would recommend writing this little hint into installation guide for all the newbe's like me. Thanks anyway :)
