### ISSUE TITLE
Reactive_nav_2d implementation in a differential drive bot 

### ISSUE THREAD

**Issue by prodeel** [MRPT/mrpt#705]
How do I implement mrpt reactive_nav in a differential bot in ROS.

**Comment by jlblancoc** [comment]
Hi, 

[mrpt_reactivenav2d](http://wiki.ros.org/mrpt_reactivenav2d) is the node you need to launch. See the example .launch and .ini files provided in that package as a start point. The node will publish `cmd_vel` commands (Twist2D) as it's common in ROS, so as long as your robot is able to process those commands, and you feed obstacles (as pointclouds) to the reactive node, it should work.

**Comment by prodeel** [comment]
Thank-you sir.
