### ISSUE TITLE
Bundle Adjustment

### ISSUE THREAD

**Issue by donesaricameverest** [MRPT/mrpt#712]
Hello ,
I tried bundle adjustment demo with the input i gave (feats.txt) and set camera params like below. Then I got result(bundeledPoints.txt). I expected to see distance between each pair point 50 mm in result. But it isn't. How can I get metric result?

camera_params.setIntrinsicParamsFromValues(4.7509750263766691e+03, 4.7559600160738355e+03, 1.1377659970206614e+03, 1.1203296285145784e+03);
				
				camera_params.ncols = 2040;
				camera_params.nrows = 2040;

				camera_params.dist[0] = -1.0952366447451505e-01;
				camera_params.dist[1] = -7.7208030577895370e-01;
				camera_params.dist[2] = 0.;
				camera_params.dist[3] = 0.;
				camera_params.dist[4] = 3.3547399372271101e+00;
				camera_params.focalLengthMeters = 0.012;

[feats.txt](https://github.com/MRPT/mrpt/files/1899457/feats.txt)
[bundeledPoints.txt](https://github.com/MRPT/mrpt/files/1906087/bundeledPoints.txt)

**Comment by jlblancoc** [comment]
Hi Done,

Using monocular SLAM / SfT / Bundle Adjustment (I would say all three are different names to basically the same set of techniques) one CANNOT obtain *absolute* distances. This is a "theoretical" limit: with one camera the reconstructured 3D world can be accurate but up to a **scale factor**. 

State of the art algorithms in the computer vision and SLAM communities address this by means of tons of different methods (none of them in MRPT at present...): using the scale or depth of a predefined pattern during initialization, optimizing using Sim(3) Lie Group to avoid scale drift errors during a long loop after loop closure, etc. 

Hope I "helped" somehow...
Cheers

PS: Also, the "camera_params" field `focalLengthMeters` is not actually used for Bundle Adjustment. Instead, the "fx" and "fy" fields (focal lengths in "pixel units") are important to fill. See for example [this](https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html)
