### ISSUE TITLE
Turn some apps into C++ classes so they can be reused in unit tests & mrpt_performance

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#714]
This will allow cleaning up duplicated code, adding new tests, and increasing code coverage.

List of candidates: 
* [x] pf-localization
* [x] icp-slam
* [x] icp-slam-live
* [x] rbpf-slam
* [x] graph-slam-engine (already done?)
* [x] map-partition -> not worth. Using regular unit tests of the underlying class instead.
* [x] grid-matching
* [x] kf-slam
* [x] rawlog-grabber

**Comment by jolting** [comment]
Also for reuse in future Web UIs.
