### ISSUE TITLE
use error

### ISSUE THREAD

**Issue by cumtchenchang** [MRPT/mrpt#717]
CMake Error at /usr/share/mrpt/MRPTConfig.cmake:223 (MESSAGE):
  ERROR: MRPT_FIND_COMPONENTS contains 'mrpt-base', not built in mrpt (built
  ones:
  mrpt-expr;mrpt-core;mrpt-comms;mrpt-hwdrivers;mrpt-nanoflann;mrpt-bayes;mrpt-typemeta;mrpt-tfest;mrpt-db;mrpt-opengl;mrpt-containers;mrpt-tclap;mrpt-slam;mrpt-detectors;mrpt-img;mrpt-topography;mrpt-config;mrpt-gui;mrpt-kinematics;mrpt-nav;mrpt-graphslam;mrpt-io;mrpt-poses;mrpt-maps;mrpt-serialization;mrpt-rtti;mrpt-system;mrpt-hmtslam;mrpt-obs;mrpt-vision;mrpt-graphs;mrpt-math;mrpt-random)
Call Stack (most recent call first):

**Comment by jolting** [comment]
Use the 1.5 branch or read the notes for details about upgrading to the 2.0 branch.

This is similar to #615.
