### ISSUE TITLE
Bug in CLoopCloserERD

### ISSUE THREAD

**Issue by MaxGsomGsom** [MRPT/mrpt#723]
I have spent a lot of time to find why my configuration of graph slam don't work. And it seems that there should be ``if (!it->second)``.

https://github.com/MRPT/mrpt/blob/50111a08efeb0744d5e97658b30f9131c5fef5f3/libs/graphslam/include/mrpt/graphslam/ERD/CLoopCloserERD_impl.h#L2515-L2527

**Comment by jolting** [comment]
CC: @bergercookie

**Comment by bergercookie** [comment]
Yeah, this seems to be a bug.
I'm surprised this is there because it's quite big for me not to notice it.

Anyway, feel free to make a PR for this, otherwise I can patch it in the couple of days.

**Comment by MaxGsomGsom** [comment]
Also it does not compile:
https://github.com/MRPT/mrpt/blob/50111a08efeb0744d5e97658b30f9131c5fef5f3/libs/graphslam/include/mrpt/graphslam/ERD/CLoopCloserERD_impl.h#L2539-L2548

Because
https://github.com/MRPT/mrpt/blob/50111a08efeb0744d5e97658b30f9131c5fef5f3/libs/slam/include/mrpt/slam/CIncrementalMapPartitioner.h#L137-L139

**Comment by jlblancoc** [comment]
Just fixed with 630ad757efc9873f64c735f36e6afe977c2a056f

**Comment by MaxGsomGsom** [comment]
I have tried to compile again but it shows error:
``/home/max/Desktop/mrpt/libs/slam/include/mrpt/slam/CIncrementalMapPartitioner.h:137:11: note:   no known conversion for argument 2 from ‘std::__shared_ptr_access<mrpt::poses::CPosePDF, (__gnu_cxx::_Lock_policy)2, false, false>::element_type {aka mrpt::poses::CPosePDF}’ to ‘const mrpt::poses::CPose3DPDF&’``

**Comment by jolting** [comment]
That might be an explicit conversion. Try `mrpt::poses::CPose3DPDF(*posePDF)`

**Comment by jlblancoc** [comment]
Should be fixed after #726, if not please reopen...
