### ISSUE TITLE
Build error on 16.04 "m_partitioner.addMapFrame"

### ISSUE THREAD

**Issue by cressell** [MRPT/mrpt#725]
Hi,

I'm getting an error when trying to build the master branch on ubuntu 16.04 (jetson tx2). I have updated gcc+.

`error: no matching function for call to ‘mrpt::slam::CIncrementalMapPartitioner::addMapFrame(mrpt::obs::CSensoryFrame&, std::__shared_ptr_access<mrpt::poses::CPosePDF, (__gnu_cxx::_Lock_policy)2, false, false>::element_type&)’
   m_partitioner.addMapFrame(sf, *posePDF);`

Above is the error I'm getting. Any clues?

Regards,
Cressell

**Comment by jlblancoc** [comment]
This should be fixed after #726 , if not let us know... thanks!
