### ISSUE TITLE
Build failed: missing cvd/config.h

### ISSUE THREAD

**Issue by cressell** [MRPT/mrpt#730]
Hi,
trying to build the latest commit (was fine yesterday!), getting the following error:
```
In file included from /home/nvidia/mrpt/libs/opengl/src/gl_utils.cpp:16:0:
/home/nvidia/mrpt/otherlibs/libcvd/cvd/gl_helpers.h:15:10: fatal error: cvd/config.h: No such file or directory
 #include <cvd/config.h>
          ^~~~~~~~~~~~~~
compilation terminated.

```
Any clues?
Regards,
Cressell

**Comment by jolting** [comment]
This is suppose to add that to your include path.
https://github.com/MRPT/mrpt/blob/8c479269b7b3b14aafaa39f57c54f2a2bd7c30e8/cmakemodules/script_cvd.cmake#L17
and
https://github.com/MRPT/mrpt/blob/8c479269b7b3b14aafaa39f57c54f2a2bd7c30e8/libs/opengl/CMakeLists.txt#L60

Check that directory in your build path to make sure config.h is getting generated.

**Comment by jolting** [comment]
Seems like a bug on 16.04.
Can you run find -name config.h in your build directory and send me the results?
I can fix that later.

**Comment by jolting** [comment]
Woops. It was caused by a stale bin dir in the vision library. It should be fixed now.
