### ISSUE TITLE
CFeatureLines compilation error.

### ISSUE THREAD

**Issue by lasdasdas** [MRPT/mrpt#745]
Is this WIP?, branch master is not compiling right now. 

**‘mrpt::vision::VISION_IMPEXP mrpt::vision::CFeatureLines’ has initializer but incomplete type
         class VISION_IMPEXP CFeatureLines** This was done in the last PR  #742

**Comment by jlblancoc** [comment]
It was merged too fast... 

It's been fixed in this PR: #741 . So, I'm also closing your proposal in #746 . Thanks!!
