### ISSUE TITLE
Use c++17 nested namespaces

### ISSUE THREAD

**Issue by jolting** [MRPT/mrpt#752]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4230.html

don't
```
namespace mrpt
{
namespace gui
{

}
}
```
do
```
namespace mrpt::gui
{

}
```

**Comment by jlblancoc** [comment]
Yes, that's was in my wish list :-) 
However, it would be great to do it in some automated way via scripting. I was doubting about trying to do it with regex, or via a python script or alike.... 🤔 

among other things, it will save hundreds of LOC ;-)

**Comment by bergercookie** [comment]
>However, it would be great to do it in some automated way via scripting. I was doubting about trying to do it with regex, or via a python script or alike.... thinking

I thought this to be a good usecase for `clang-tidy modernise` but as far as I can tell it doesn't support this kind of "modernisation"
