### ISSUE TITLE
Add CMake support for clang/g++ sanitizers

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#761]
I recently discovered the clang / gcc sanitizer tools (e.g., [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html).

They seem to have lots of potential when debugging our applications/unittests. There's also this [demo by lefticus](https://www.youtube.com/watch?v=MB6NPkB4YVs) demonstrating them.

I was thinking of adding options in the  CMake for using this [sanitizers-cmake](https://github.com/arsenm/sanitizers-cmake) repository. I could add it as an 3rd party submodule and optionally build it when a developer wants to debug a specific application / unittest.

It may also make sense to turn them on when running the unittests in the CI.

Is this something we 're interested in?

**Comment by jolting** [comment]
It's been used in the past. #633

**Comment by jlblancoc** [comment]
Hi @bergercookie !

Yes, we knew them, and have been **extremely** useful (together with valgrind) debugging some hidden bugs in unit tests and apps. 

I thought in adding them via CMake options, as you propose, but in the end I think it's better not to do it:  these tools are really only for MRPT developers, and there are many complex ways of combining different sanitizers (and perhaps more to come in future versions of gcc?). Some sanitizers are incompatible within them; and using any of them is incompatible with valgrind.

So, just manually adding the corresponding build flags to CMake is enough, IMO. 

Also, I wrote this gist to make it almost immediate ;-)
https://gist.github.com/jlblancoc/44be9d4d466f0a973b1f3808a8e56782

**Comment by bergercookie** [comment]
Yes, we knew them, and have been extremely useful (together with valgrind) debugging some hidden bugs in unit tests and apps.

Hah, should have made a querry in the issues rather than just running grep in the codebase!

> So, just manually adding the corresponding build flags to CMake is enough, IMO.

Sure, sounds fine! :-)
