### ISSUE TITLE
error: ‘mutex’ in namespace ‘std’ does not name a type [Ubuntu, c++17, gcc 7.3]

### ISSUE THREAD

**Issue by JGMonroy** [MRPT/mrpt#777]
After upgrading to C++17 and GCC 7.3.0 we started getting issues with the hmtslam-lib and some references to mutex. The exact error is: 
`error: ‘mutex’ in namespace ‘std’ does not name a type `

For example [here](https://github.com/MRPT/mrpt/blob/8df78bb868d9753099206eab2e1228ef36f1e41f/libs/hmtslam/include/mrpt/hmtslam/CLocalMetricHypothesis.h#L92) on the CLocalMetricHypothesis.h

Googling it I found that a mere `#include <mutex>` solves the problem.

Before doing a PR I wanted to check that this is a suitable solution.

**Comment by jlblancoc** [comment]
Yes, please, go on with the PR!

That's the kind of errors when some headers are not too often tested **outside** mrpt itself... Thanks!
