### ISSUE TITLE
Missing include files in Visual Studio 2015 x64 precompiled package

### ISSUE THREAD

**Issue by JekaS178RUS** [MRPT/mrpt#780]
Hello!

I just downloaded x64 precompiled packeage from [download page](https://www.mrpt.org/download-mrpt/) and I found that under include catalog there is only 2 files:
mrpt\mrpt-config\mrpt\config.h
mrpt\mrpt-config\mrpt\version.h
And nothing more.

Also I found other include files under libs/<name>/include/mrpt directory.
It looks like someone forgot to copy those files, or I am miss something?

**Comment by jlblancoc** [comment]
Hi, 

No, that's correct. In large packages (for example, mrpt or opencv), headers are split in modules for the sake of modularity. 

If you use CMake, it will automatically add to the list of "include directories" all those really required by your applications. 

Please, see: https://www.mrpt.org/Writing_applications_with_the_MRPT_C%2B%2B_Library
