### ISSUE TITLE
Cherry-pick thread priority from mrpt-1.5

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#792]
To do: Import these functions into a new mrpt/system/thread.h header in mrpt2 : 
* [x]  changeCurrentThreadPriority()
* [x] changeCurrentProcessPriority()
  
From: a55062345383ce0c73587aebd06ed006355d4a45

**Comment by jolting** [comment]
Oh right. We got rid of the thread header.

Perhaps the header file should be called system/scheduler.h to avoid the suggestion that it's actually a thread implementation.

**Comment by jlblancoc** [comment]
Good name. I buy it.

PS: I'll add it when time permits, this ticket was just to make sure I
don't forget this (again...).
