### ISSUE TITLE
MRPT Graph Slam Minimal Example

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#806]
See: 
https://stackoverflow.com/questions/51421935/mrpt-graph-slam-minimal-example

@bergercookie  is the minimal example something like [`apps/graphslam-engine`](https://github.com/MRPT/mrpt/tree/master/apps/graphslam-engine) or do you have something else?

**Comment by bergercookie** [comment]
Yeah, the minimal example would be apps/graphslam-engine for now.

Gave a more in-detail answer in the SO issue. :-)

**Comment by jlblancoc** [comment]
Thanks!! 👍
