### ISSUE TITLE
wxwidgets is missing in prebuilt binaries for MRPT 1.5.6 vc140 x64

### ISSUE THREAD

**Issue by bpoebiapl** [MRPT/mrpt#807]
Hi. I was able to get prebuilt binaries for vc140 x64 from the link below.
https://github.com/MRPT/mrpt/releases/download/1.5.6/mrpt-1.5.6-msvc14-x64.exe
I found a problem with using the mrpt::gui related module that I downloaded and installed through the link, and I found that MRPT_HAS_WXWIDGETS is set to 0 in the mrpt / config.h file.
I tried to build it on my own but it failed and so I decided to use version 1.5.5 first for now.
If this problem is resolved, I would like to try prebuilt binaries 1.5.6.
At the same time I'm going to try to build it using vcpkg.

**Comment by jlblancoc** [comment]
This problem is confirmed. It was due to an error during the deployment of last release's binary packages. If someone makes any progress towards a better way to distribute windows binaries (vcpkg?), feel free of opening a PR! ;-)

Otherwise, binaries will be regenerated for the next release v1.5.7.
