### ISSUE TITLE
ransac c++ example

### ISSUE THREAD

**Issue by caoxudong0513** [MRPT/mrpt#826]
hello，where can i find the examples of ransac？https://github.com/MRPT/mrpt/tree/master/samples/ransac-demo-applications.
thank you very much

**Comment by jlblancoc** [comment]
Hi, 

https://github.com/MRPT/mrpt/tree/master/samples/math_ransac_examples
and
https://github.com/MRPT/mrpt/tree/master/samples/math_ransac_plane3d_example

Please, let me know of any broken link pointing to the old URLs to fix it.
