### ISSUE TITLE
problem when make on ubuntu

### ISSUE THREAD

**Issue by wanderhlx** [MRPT/mrpt#833]
I have tried to build mrpt on ubuntu16.04,but meet some problems when make:
[ 71%] Building CXX object libs/hwdrivers/CMakeFiles/mrpt-hwdrivers.dir/src/aria/src/ArTcpConnection.cpp.o
/home/hlx/package/mrpt/apps/ReactiveNavigationDemo/reactive_navigator_demoMain.cpp:335:100: error: ‘wxTE_AUTO_SCROLL’ was not declared in this scope
     edLog = new wxTextCtrl(Panel2, ID_TEXTCTRL5, wxEmptyString, wxDefaultPosition, wxSize(612,85), wxTE_AUTO_SCROLL|wxTE_MULTILINE|wxTE_READONLY|wxTE_DONTWRAP|wxALWAYS_SHOW_SB, wxDefaultValidator, _T("ID_TEXTCTRL5"));
/home/hlx/package/mrpt/apps/ReactiveNavigationDemo/reactive_navigator_demoMain.cpp:1042:102: error: ‘wxTE_AUTO_SCROLL’ was not declared in this scope
    edWpLog = new wxTextCtrl(wxFrWpInfo,wxNewId(), wxEmptyString, wxDefaultPosition, wxSize(400,150), wxTE_AUTO_SCROLL|wxTE_MULTILINE|wxTE_READONLY|wxTE_DONTWRAP|wxALWAYS_SHOW_SB, wxDefaultValidator, _T("ID_TEXTCTRL_WP"));
.........
[ 82%] Building CXX object libs/hwdrivers/CMakeFiles/mrpt-hwdrivers.dir/src/CVelodyneScanner.cpp.o
/home/hlx/package/mrpt/libs/hwdrivers/src/CGenericSensor.cpp:26:11: warning: ‘dumm’ defined but not used [-Wunused-variable]
 const int dumm = mrpt_hwdrivers_class_reg.do_nothing(); // Avoid compiler removing this class in static linking
           ^
[ 82%] Linking CXX shared library ../../lib/libmrpt-hwdrivers.so
[ 82%] Built target mrpt-hwdrivers
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Is there any solutions?

**Comment by jlblancoc** [comment]
Are you building the  `master` or `mrpt-1.5` branch of mrpt? 
What version of wxWidgets do you have installed?

> Is there any solutions?

There's **always** a solution ;-)

**Comment by wanderhlx** [comment]
Sorry I can't tell the which branch of mrpt I'm building, the author of PL-SLAM offered a website of mrpt, he said if we use the most recent versions of the MRPT library we might find some issues due to hard refactoring,and the website is:
https://github.com/MRPT/mrpt/tree/0c3d605c3cbf5f2ffb8137089e43ebdae5a55de3
I think It's mrpt-1.3 or mrpt-1.4.....
And the version of wxWidgets is 2.8
> There's always a solution ;-)
That is very inspiring

**Comment by jlblancoc** [comment]
Try checking out the [mrpt-1.5 branch](https://github.com/MRPT/mrpt/tree/mrpt-1.5), it should be compatible and perhaps it fixes that wxWidgets error. 
If not, we could address and fix it in the mrpt-1.5 branch.

PS: Or even better... give it a try to the mrpt-1.5 PPA and directly install the precompiled version of mrpt, so you avoid all these problems  (!).

**Comment by jlblancoc** [comment]
Progress on this topic: 
* https://github.com/rubengooj/stvo-pl/pull/15

I think we can now close this ticket, since pl-slam could be now built against the latest mrpt-1.5 branch. Notice that, as of today, there're other g2o-related build problems, discussed in other issue threads of the original repo.
