### ISSUE TITLE
Build is broken for non amd64

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#837]
See: https://launchpad.net/~joseluisblancoc/+archive/ubuntu/mrpt/+packages

```
/<<PKGBUILDDIR>>/libs/hmtslam/src/THypothesisIDSet.cpp:21:28: error: ambiguous overload for ‘operator<<’ (operand types are ‘mrpt::serialization::CArchive’ and ‘long int’)
  for (long it : *this) out << it;
```

PS: Should we add an non- amd64 docker image to circleCI?

**Comment by jolting** [comment]
I'm not sure who maintains a 32-bit base image. A quick google search shows several which haven't been updated in quite some time.

**Comment by jlblancoc** [comment]
@jolting : Ok, let's just let it be... we might get notified of this kind of errors by PPA builders anyway. Thanks!
