### ISSUE TITLE
CMAKE error

### ISSUE THREAD

**Issue by Adlirrahaman** [MRPT/mrpt#880]
When i tried to catkin_make there was an error like : 

-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  The CMAKE_CXX_COMPILER:

    /usr/bin/c++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

then i tried to roslaunch the package , there was another error :

... logging to /home/adlir/.ros/log/c31c20d2-fe3a-11e8-9ee4-90cdb63a51ff/roslaunch-adlir-Boot-31694.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:34555/

SUMMARY
========

PARAMETERS
 * /base_frame_id: /base_link
 * /ellipse_scale: 1
 * /global_frame_id: /map
 * /ini_filename: /home/adlir/catki...
 * /odom_frame_id: /odom
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 50.0
 * /robot_state_publisher/tf_prefix: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    mrpt_ekf_slam_2d (mrpt_ekf_slam_2d/mrpt_ekf_slam_2d)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [31707]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c31c20d2-fe3a-11e8-9ee4-90cdb63a51ff
process[rosout-1]: started with pid [31720]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [31737]
**ERROR: cannot launch node of type [mrpt_ekf_slam_2d/mrpt_ekf_slam_2d]: can't locate node [mrpt_ekf_slam_2d] in package [mrpt_ekf_slam_2d]**
process[rviz-4]: started with pid [31738]

can you help me ?

**Comment by jolting** [comment]
Are you missing the build-essential package?
Try `sudo apt install build-essential`

**Comment by Adlirrahaman** [comment]
> Are you missing the build-essential package?
> Try `sudo apt install build-essential`

i've install that package but still same

**Comment by Adlirrahaman** [comment]
maybe i missing that package , how can i found that

**Comment by Adlirrahaman** [comment]
maybe i missing that package , how can i found that?

**Comment by jolting** [comment]
Normally on Ubuntu this is managed by alternatives, so it should look something like this:
```
$ readlink /usr/bin/c++
/etc/alternatives/c++
$ readlink /etc/alternatives/c++
/usr/bin/g++
```

**Comment by jolting** [comment]
If you want to set your c++ alternative you should run
```
sudo update-alternatives --config c++
```
and for consistency
```
sudo update-alternatives --config cc
```
It is certainly is not recommended on an Ubuntu machine to manually edit your symlinks.

**Comment by Adlirrahaman** [comment]
> Normally on Ubuntu this is managed by alternatives, so it should look something like this:
> 
> ```
> $ readlink /usr/bin/c++
> /etc/alternatives/c++
> $ readlink /etc/alternatives/c++
> /usr/bin/g++
> ```
then if its same ? i allready check it then its same but still didnt work

**Comment by jlblancoc** [comment]
From [this](https://stackoverflow.com/questions/45140273/cmake-c-compiler-is-not-a-full-path-to-an-existing-compiler-tool), try: `apt-get install --reinstall gcc`. 

Anyway, I'm afraid the problem is not directly related to MRPT, so I'll close the ticket, ok? You probably could find a better guess of how to solve your problem by asking in StackOverflow or some other more general forum. In any case, remember to tell what has taken you to this point: you probably manually set/installed/... some compiler packages, and that must be the key to what was broken...

Cheers.
