### ISSUE TITLE
assimp-mrpt-vc140-mt.dll missing from 1.5.7 x64 release

### ISSUE THREAD

**Issue by ahtur** [MRPT/mrpt#917]
HI. camera-calib cannot start because assimp-mrpt-vc140-mt.dll isn't found. Could you please add it to the bundle ?

**Comment by jlblancoc** [comment]
Hi, 
Thanks for reporting. Indeed it was a bug in the script for generating Windows packages. 
It's fixed now. Please, re-download the package: https://github.com/MRPT/mrpt/releases/download/1.5.7/mrpt-1.5.7-msvc15-x64.exe
