### ISSUE TITLE
Compilation error: expression ‘<throw-expression>’ is not a constant-expression   throw Exceptions::BadSubscript();

### ISSUE THREAD

**Issue by dibet** [MRPT/mrpt#948]
Hi, i'am trying to compile but i get the following error in the third party library CVD

[  1%] Building CXX object CMakeFiles/CVD.dir/cvd_src/bayer.cxx.o
In file included from /home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/image_ref.h:185:0,
                 from /home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/image.h:17,
                 from /home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/image_convert_fwd.h:4,
                 from /home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/colourspace_convert.h:3,
                 from /home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd_src/bayer.cxx:3:
/home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/internal/image_ref_implementation.hh: In member function ‘constexpr int& CVD::ImageRef::operator[](int)’:
/home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/internal/image_ref_implementation.hh:193:33: error: expression ‘<throw-expression>’ is not a constant-expression
  throw Exceptions::BadSubscript();
                                 ^
/home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/internal/image_ref_implementation.hh: In member function ‘constexpr int CVD::ImageRef::operator[](int) const’:
/home/dibet/projects/mola/mrpt/otherlibs/libcvd/cvd/internal/image_ref_implementation.hh:203:36: error: expression ‘<throw-expression>’ is not a constant-expression
     throw Exceptions::BadSubscript();
                                    ^
CMakeFiles/CVD.dir/build.make:62: recipe for target 'CMakeFiles/CVD.dir/cvd_src/bayer.cxx.o' failed
make[5]: *** [CMakeFiles/CVD.dir/cvd_src/bayer.cxx.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/CVD.dir/all' failed
make[4]: *** [CMakeFiles/CVD.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/libcvd.dir/build.make:110: recipe for target 'libcvd-prefix/src/libcvd-stamp/libcvd-build' failed
make[2]: *** [libcvd-prefix/src/libcvd-stamp/libcvd-build] Error 2
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/libcvd.dir/all' failed
make[1]: *** [CMakeFiles/libcvd.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Thanks

**Comment by jolting** [comment]
which compiler and Linux distro are you using?

**Comment by dibet** [comment]
I was using gcc 7.4 and ubuntu 16.04, but i will change to 18.04 right now...

**Comment by jlblancoc** [comment]
Will close since we can't reproduce the failure... feel free of reopening if the problem persists and there's a way to reproduce it.
