### ISSUE TITLE
Cmake Error(wxWidgets: No gtk3 version found, falling back to default (likely gtk2))

### ISSUE THREAD

**Issue by nofear123** [MRPT/mrpt#964]
My computer is Ubuntu 16.04LTS. When I installed the master branch, I can't locate libwxgtk3.0-gtk3-dev according to the operation. So the following error occurred.

-- Kernel name (uname -s): Linux

          Warning: No config found to match: /usr/bin/wx-config --selected-config --toolkit=gtk3
                   in /usr/lib/x86_64-linux-gnu/wx/config
          If you require this configuration, please install the desired
          library build.  If this is part of an automated configuration
          test and no other errors occur, you may safely ignore it.
          You may use wx-config --list to see all configs available in
          the default prefix.

-- wxWidgets: No gtk3 version found, falling back to default (likely gtk2)
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- clang-tidy: not using. CMake version must be >=3.6
-- iwyu (include-what-you-use) not found.
CMake Error at CMakeLists.txt:398 (message):
  MRPT requires gcc-7 or above.  Please, see instructions for upgrading in:
  https://github.com/MRPT/mrpt/blob/master/README.md#32-build-from-sources

-- Configuring incomplete, errors occurred!
See also "/home/wang/MPRT/mrpt/CMakeFiles/CMakeOutput.log".
See also "/home/wang/MPRT/mrpt/CMakeFiles/CMakeError.log".

**Comment by jlblancoc** [comment]
Hi,
The only actual error there is that you need to install GCC 7, please refer to instructions in the root readme.
Cheers

**Comment by nofear123** [comment]
thanks
